name: CI - CPU Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cpu-tests:
    runs-on: [self-hosted, Linux, X64]
    container:
      image: 763104351884.dkr.ecr.ap-southeast-1.amazonaws.com/pytorch-training:2.6.0-gpu-py312

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=150
        
      - name: Run tests
        run: |
          pip install pytest
          pytest -m "cpu and not gpu" --maxfail=1 --disable-warnings -q