name: CI - GPU Tests

on:
  schedule:
    - cron: '2 0 * * *'
jobs:
  gpu-tests:
    runs-on: [self-hosted, GPU, Linux, X64]
    container:
      image: 763104351884.dkr.ecr.ap-southeast-1.amazonaws.com/pytorch-training:2.6.0-gpu-py312

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run tests
        run: |
          pip install pytest
          pytest -m "gpu" --maxfail=1 --disable-warnings -q